
/*=============================================*
 *              OP.H                           *
 *                                             * 
 * This file contains the declarations for     *
 * for the jsp operations                      *
 *=============================================*/

#ifndef OP
#define OP
#include <stdio.h>
#include "structs.h"

/*******
********        FUNCTION DECLARATIONS
********/

extern OPLIST *create_op(void);

#endif


